# Generated by Django 4.2.9 on 2024-01-26 11:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_alter_post_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("user", "message")},
        ),
    ]
