# Generated by Django 4.2.9 on 2024-01-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_description"),
        ("posts", "0004_alter_post_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="groups.group",
            ),
        ),
    ]
